### PR TITLE
Update proxy.py

### PR DESCRIPTION
**Pull request by skaface**
Additional fix for "unterminated quoted string" error

### CODE REVIEW

**Comment by skaface** [comment]
I hope I did this correctly, its the first time I have contributed to a project

**Comment by skaface** [comment]
Just to note, I was still receiving the same error that I mentioned after your recent code changes, but I have confirmed that this has fixed the error

**Comment by matthuisman** [comment]
thanks for this. can you please try the latest master code and see if that works?

**Comment by skaface** [comment]
Yes it is all good now. Thanks

**Pull request closed without merging**
